fix: dynamo batch write unprocessed
elastic-ipfs/indexer-lambda pull request #70
Opened 2022-10-17 13:03 UTC by simone-sanfratello

2022-10-17 14:01 UTC, francardoso93 requested changes

2022-10-17 14:16 UTC, simone-sanfratello commented on src/lib/storage.js
> +    } while (!done)
Not sure it's the right thing to do, according to documentation, the unprocessed items should be processed again until they success

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html

Which cases do you think need a max retries?

2022-10-17 14:17 UTC, simone-sanfratello commented on src/lib/storage.js
> +    } while (!done)
Also consider, the batch size is 25

2022-10-17 14:42 UTC, francardoso93 approved these changes

2022-10-17 17:32 UTC, fabiolrodriguez approved these changes

2022-10-18 13:08 UTC, blucas approved these changes
Looks good.  Minor question though.

2022-10-18 13:08 UTC, blucas commented on src/lib/storage.js
> +        logger.warn({ UnprocessedItems: JSON.stringify(response.UnprocessedItems) }, 'UnprocessedItems in BatchWriteItemCommand')
Question: Do we want to consider this a `warn` or an `info`?  If AWS treats this as a normal occurrence, then we may as well also.

2022-10-18 13:08 UTC, blucas commented on src/lib/storage.js
> +    } while (!done)
I think `maxRetries` may be of worth _if_ we believe that AWS may never successfully process all our items.  In that case, we'd be stuck in an endless loop.  My assumption is that all these items will successfully process.

2022-10-18 14:12 UTC, merged